package enums;

public enum Escolaridade {
    FUNDAMENTAL_INCOMPLETO,
    FUNDAMENTAL_COMPLETO,
    ENSINO_MEDIO_INCOMPLETO,
    ENSINO_MEDIO_COMPLETO,
    ENSINO_SUPERIOR_INCOMPLETO,
    ENSINO_SUPERIOR_COMPLETO,

}
